using System;
using System.Collections.Generic;

namespace Project_Euler_02
{
    class Program
    {
        static void Main(string[] args)
        {
            /* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
             * By starting with 1 and 2, the first 10 terms will be
             * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...   
             * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
             * find the sum of the even-valued terms. */

            /*
             * Stop alle getallen in een List en geef ze een index
             * Tel de laatste en ena laatste bij elkaar op en verhoog dan steeds de index.
             * Sla alleen de even aantalen op en ga verder tot 4 mil wordt bereikt.
             * Laat eindresultaat zien.
             */
            
            // Setup starting situation list: (1, 2 ,3)
            List<int> sequence = new List<int> { 1, 2 };

            int sum = sequence[0] + sequence[1];
            sequence.Insert(2, sum);

            
            // Steeds 1 stapje opschuiven, herberekenen en toevoegen. Stop bij 4 miljoen.
            
            int i = 0;

            while (true)
            {
                i++;

                Console.WriteLine("Old sum = " + sum);
                
                sum = sequence[0 + i] + sequence[1 + i];

                if (sum < 4000000)
                {
                    sequence.Insert(2 + i, sum);

                    Console.WriteLine("New sum = " + sum);
                }
                else
                {
                    break;
                }

            }


            // Zoek alle even getallen en tel ze op
            int evenNumbers = 0;
            foreach (var number in sequence)
            {
                if (number % 2 == 0)
                {
                    evenNumbers += number;
                    Console.WriteLine("Even number = " + number);
                }
                else
                {
                    // do nothing
                }
            }

            Console.WriteLine("Total = " + evenNumbers);
            Console.ReadLine();

        }
    }
}
